#ifdef _WIN32
#include <windows.h>
#define LOAD_LIBRARY LoadLibraryA("vulkan-1.dll")
#define GET_PROC_ADDR GetProcAddress
#else
#include <dlfcn.h>
#define LOAD_LIBRARY dlopen("libvulkan.so", RTLD_NOW)
#define GET_PROC_ADDR dlsym
#endif

typedef void* (*fn)();

void* lib;

fn vkCreateInstance;
fn vkEnumerateInstanceExtensionProperties;
fn vkEnumerateInstanceLayerProperties;
fn vkEnumerateInstanceVersion;
fn vkBeginCommandBuffer;
fn vkEndCommandBuffer;
fn vkResetCommandBuffer;
fn vkCmdBindPipeline;
fn vkCmdSetViewport;
fn vkCmdSetScissor;
fn vkCmdSetLineWidth;
fn vkCmdSetDepthBias;
fn vkCmdSetBlendConstants;
fn vkCmdSetDepthBounds;
fn vkCmdSetStencilCompareMask;
fn vkCmdSetStencilWriteMask;
fn vkCmdSetStencilReference;
fn vkCmdBindDescriptorSets;
fn vkCmdBindIndexBuffer;
fn vkCmdBindVertexBuffers;
fn vkCmdDraw;
fn vkCmdDrawIndexed;
fn vkCmdDrawIndirect;
fn vkCmdDrawIndexedIndirect;
fn vkCmdDispatch;
fn vkCmdDispatchIndirect;
fn vkCmdCopyBuffer;
fn vkCmdCopyImage;
fn vkCmdBlitImage;
fn vkCmdCopyBufferToImage;
fn vkCmdCopyImageToBuffer;
fn vkCmdUpdateBuffer;
fn vkCmdFillBuffer;
fn vkCmdClearColorImage;
fn vkCmdClearDepthStencilImage;
fn vkCmdClearAttachments;
fn vkCmdResolveImage;
fn vkCmdSetEvent;
fn vkCmdResetEvent;
fn vkCmdWaitEvents;
fn vkCmdPipelineBarrier;
fn vkCmdBeginQuery;
fn vkCmdEndQuery;
fn vkCmdResetQueryPool;
fn vkCmdWriteTimestamp;
fn vkCmdCopyQueryPoolResults;
fn vkCmdPushConstants;
fn vkCmdBeginRenderPass;
fn vkCmdNextSubpass;
fn vkCmdEndRenderPass;
fn vkCmdExecuteCommands;
fn vkCmdSetDeviceMask;
fn vkCmdDispatchBase;
fn vkCmdDrawIndirectCount;
fn vkCmdDrawIndexedIndirectCount;
fn vkCmdBeginRenderPass2;
fn vkCmdNextSubpass2;
fn vkCmdEndRenderPass2;
fn vkCmdSetDeviceMaskKHR;
fn vkCmdDispatchBaseKHR;
fn vkCmdPushDescriptorSetKHR;
fn vkCmdPushDescriptorSetWithTemplateKHR;
fn vkCmdBeginRenderPass2KHR;
fn vkCmdNextSubpass2KHR;
fn vkCmdEndRenderPass2KHR;
fn vkCmdDrawIndirectCountKHR;
fn vkCmdDrawIndexedIndirectCountKHR;
fn vkCmdDebugMarkerBeginEXT;
fn vkCmdDebugMarkerEndEXT;
fn vkCmdDebugMarkerInsertEXT;
fn vkCmdBindTransformFeedbackBuffersEXT;
fn vkCmdBeginTransformFeedbackEXT;
fn vkCmdEndTransformFeedbackEXT;
fn vkCmdBeginQueryIndexedEXT;
fn vkCmdEndQueryIndexedEXT;
fn vkCmdDrawIndirectByteCountEXT;
fn vkCmdDrawIndirectCountAMD;
fn vkCmdDrawIndexedIndirectCountAMD;
fn vkCmdBeginConditionalRenderingEXT;
fn vkCmdEndConditionalRenderingEXT;
fn vkCmdSetViewportWScalingNV;
fn vkCmdSetDiscardRectangleEXT;
fn vkCmdBeginDebugUtilsLabelEXT;
fn vkCmdEndDebugUtilsLabelEXT;
fn vkCmdInsertDebugUtilsLabelEXT;
fn vkCmdSetSampleLocationsEXT;
fn vkCmdBindShadingRateImageNV;
fn vkCmdSetViewportShadingRatePaletteNV;
fn vkCmdSetCoarseSampleOrderNV;
fn vkCmdBuildAccelerationStructureNV;
fn vkCmdCopyAccelerationStructureNV;
fn vkCmdTraceRaysNV;
fn vkCmdWriteAccelerationStructuresPropertiesKHR;
fn vkCmdWriteAccelerationStructuresPropertiesNV;
fn vkCmdWriteBufferMarkerAMD;
fn vkCmdDrawMeshTasksNV;
fn vkCmdDrawMeshTasksIndirectNV;
fn vkCmdDrawMeshTasksIndirectCountNV;
fn vkCmdSetExclusiveScissorNV;
fn vkCmdSetCheckpointNV;
fn vkCmdSetPerformanceMarkerINTEL;
fn vkCmdSetPerformanceStreamMarkerINTEL;
fn vkCmdSetPerformanceOverrideINTEL;
fn vkCmdSetLineStippleEXT;
fn vkCmdSetCullModeEXT;
fn vkCmdSetFrontFaceEXT;
fn vkCmdSetPrimitiveTopologyEXT;
fn vkCmdSetViewportWithCountEXT;
fn vkCmdSetScissorWithCountEXT;
fn vkCmdBindVertexBuffers2EXT;
fn vkCmdSetDepthTestEnableEXT;
fn vkCmdSetDepthWriteEnableEXT;
fn vkCmdSetDepthCompareOpEXT;
fn vkCmdSetDepthBoundsTestEnableEXT;
fn vkCmdSetStencilTestEnableEXT;
fn vkCmdSetStencilOpEXT;
fn vkCmdPreprocessGeneratedCommandsNV;
fn vkCmdExecuteGeneratedCommandsNV;
fn vkCmdBindPipelineShaderGroupNV;
fn vkQueueSubmit;
fn vkQueueWaitIdle;
fn vkQueueBindSparse;
fn vkQueuePresentKHR;
fn vkQueueBeginDebugUtilsLabelEXT;
fn vkQueueEndDebugUtilsLabelEXT;
fn vkQueueInsertDebugUtilsLabelEXT;
fn vkGetQueueCheckpointDataNV;
fn vkQueueSetPerformanceConfigurationINTEL;
fn vkGetDeviceProcAddr;
fn vkDestroyDevice;
fn vkGetDeviceQueue;
fn vkDeviceWaitIdle;
fn vkAllocateMemory;
fn vkFreeMemory;
fn vkMapMemory;
fn vkUnmapMemory;
fn vkFlushMappedMemoryRanges;
fn vkInvalidateMappedMemoryRanges;
fn vkGetDeviceMemoryCommitment;
fn vkBindBufferMemory;
fn vkBindImageMemory;
fn vkGetBufferMemoryRequirements;
fn vkGetImageMemoryRequirements;
fn vkGetImageSparseMemoryRequirements;
fn vkCreateFence;
fn vkDestroyFence;
fn vkResetFences;
fn vkGetFenceStatus;
fn vkWaitForFences;
fn vkCreateSemaphore;
fn vkDestroySemaphore;
fn vkCreateEvent;
fn vkDestroyEvent;
fn vkGetEventStatus;
fn vkSetEvent;
fn vkResetEvent;
fn vkCreateQueryPool;
fn vkDestroyQueryPool;
fn vkGetQueryPoolResults;
fn vkCreateBuffer;
fn vkDestroyBuffer;
fn vkCreateBufferView;
fn vkDestroyBufferView;
fn vkCreateImage;
fn vkDestroyImage;
fn vkGetImageSubresourceLayout;
fn vkCreateImageView;
fn vkDestroyImageView;
fn vkCreateShaderModule;
fn vkDestroyShaderModule;
fn vkCreatePipelineCache;
fn vkDestroyPipelineCache;
fn vkGetPipelineCacheData;
fn vkMergePipelineCaches;
fn vkCreateGraphicsPipelines;
fn vkCreateComputePipelines;
fn vkDestroyPipeline;
fn vkCreatePipelineLayout;
fn vkDestroyPipelineLayout;
fn vkCreateSampler;
fn vkDestroySampler;
fn vkCreateDescriptorSetLayout;
fn vkDestroyDescriptorSetLayout;
fn vkCreateDescriptorPool;
fn vkDestroyDescriptorPool;
fn vkResetDescriptorPool;
fn vkAllocateDescriptorSets;
fn vkFreeDescriptorSets;
fn vkUpdateDescriptorSets;
fn vkCreateFramebuffer;
fn vkDestroyFramebuffer;
fn vkCreateRenderPass;
fn vkDestroyRenderPass;
fn vkGetRenderAreaGranularity;
fn vkCreateCommandPool;
fn vkDestroyCommandPool;
fn vkResetCommandPool;
fn vkAllocateCommandBuffers;
fn vkFreeCommandBuffers;
fn vkBindBufferMemory2;
fn vkBindImageMemory2;
fn vkGetDeviceGroupPeerMemoryFeatures;
fn vkGetImageMemoryRequirements2;
fn vkGetBufferMemoryRequirements2;
fn vkGetImageSparseMemoryRequirements2;
fn vkTrimCommandPool;
fn vkGetDeviceQueue2;
fn vkCreateSamplerYcbcrConversion;
fn vkDestroySamplerYcbcrConversion;
fn vkCreateDescriptorUpdateTemplate;
fn vkDestroyDescriptorUpdateTemplate;
fn vkUpdateDescriptorSetWithTemplate;
fn vkGetDescriptorSetLayoutSupport;
fn vkCreateRenderPass2;
fn vkResetQueryPool;
fn vkGetSemaphoreCounterValue;
fn vkWaitSemaphores;
fn vkSignalSemaphore;
fn vkGetBufferDeviceAddress;
fn vkGetBufferOpaqueCaptureAddress;
fn vkGetDeviceMemoryOpaqueCaptureAddress;
fn vkCreateSwapchainKHR;
fn vkDestroySwapchainKHR;
fn vkGetSwapchainImagesKHR;
fn vkAcquireNextImageKHR;
fn vkGetDeviceGroupPresentCapabilitiesKHR;
fn vkGetDeviceGroupSurfacePresentModesKHR;
fn vkAcquireNextImage2KHR;
fn vkCreateSharedSwapchainsKHR;
fn vkGetDeviceGroupPeerMemoryFeaturesKHR;
fn vkTrimCommandPoolKHR;
fn vkGetMemoryFdKHR;
fn vkGetMemoryFdPropertiesKHR;
fn vkImportSemaphoreFdKHR;
fn vkGetSemaphoreFdKHR;
fn vkCreateDescriptorUpdateTemplateKHR;
fn vkDestroyDescriptorUpdateTemplateKHR;
fn vkUpdateDescriptorSetWithTemplateKHR;
fn vkCreateRenderPass2KHR;
fn vkGetSwapchainStatusKHR;
fn vkImportFenceFdKHR;
fn vkGetFenceFdKHR;
fn vkAcquireProfilingLockKHR;
fn vkReleaseProfilingLockKHR;
fn vkGetImageMemoryRequirements2KHR;
fn vkGetBufferMemoryRequirements2KHR;
fn vkGetImageSparseMemoryRequirements2KHR;
fn vkCreateSamplerYcbcrConversionKHR;
fn vkDestroySamplerYcbcrConversionKHR;
fn vkBindBufferMemory2KHR;
fn vkBindImageMemory2KHR;
fn vkGetDescriptorSetLayoutSupportKHR;
fn vkGetSemaphoreCounterValueKHR;
fn vkWaitSemaphoresKHR;
fn vkSignalSemaphoreKHR;
fn vkGetBufferDeviceAddressKHR;
fn vkGetBufferOpaqueCaptureAddressKHR;
fn vkGetDeviceMemoryOpaqueCaptureAddressKHR;
fn vkGetPipelineExecutablePropertiesKHR;
fn vkGetPipelineExecutableStatisticsKHR;
fn vkGetPipelineExecutableInternalRepresentationsKHR;
fn vkDebugMarkerSetObjectTagEXT;
fn vkDebugMarkerSetObjectNameEXT;
fn vkGetImageViewHandleNVX;
fn vkGetImageViewAddressNVX;
fn vkGetShaderInfoAMD;
fn vkDisplayPowerControlEXT;
fn vkRegisterDeviceEventEXT;
fn vkRegisterDisplayEventEXT;
fn vkGetSwapchainCounterEXT;
fn vkGetRefreshCycleDurationGOOGLE;
fn vkGetPastPresentationTimingGOOGLE;
fn vkSetHdrMetadataEXT;
fn vkSetDebugUtilsObjectNameEXT;
fn vkSetDebugUtilsObjectTagEXT;
fn vkGetImageDrmFormatModifierPropertiesEXT;
fn vkCreateValidationCacheEXT;
fn vkDestroyValidationCacheEXT;
fn vkMergeValidationCachesEXT;
fn vkGetValidationCacheDataEXT;
fn vkCreateAccelerationStructureNV;
fn vkDestroyAccelerationStructureKHR;
fn vkDestroyAccelerationStructureNV;
fn vkGetAccelerationStructureMemoryRequirementsNV;
fn vkBindAccelerationStructureMemoryKHR;
fn vkBindAccelerationStructureMemoryNV;
fn vkCreateRayTracingPipelinesNV;
fn vkGetRayTracingShaderGroupHandlesKHR;
fn vkGetRayTracingShaderGroupHandlesNV;
fn vkGetAccelerationStructureHandleNV;
fn vkCompileDeferredNV;
fn vkGetMemoryHostPointerPropertiesEXT;
fn vkGetCalibratedTimestampsEXT;
fn vkInitializePerformanceApiINTEL;
fn vkUninitializePerformanceApiINTEL;
fn vkAcquirePerformanceConfigurationINTEL;
fn vkReleasePerformanceConfigurationINTEL;
fn vkGetPerformanceParameterINTEL;
fn vkSetLocalDimmingAMD;
fn vkGetBufferDeviceAddressEXT;
fn vkResetQueryPoolEXT;
fn vkGetGeneratedCommandsMemoryRequirementsNV;
fn vkCreateIndirectCommandsLayoutNV;
fn vkDestroyIndirectCommandsLayoutNV;
fn vkCreatePrivateDataSlotEXT;
fn vkDestroyPrivateDataSlotEXT;
fn vkSetPrivateDataEXT;
fn vkGetPrivateDataEXT;
fn vkGetAndroidHardwareBufferPropertiesANDROID;
fn vkGetMemoryAndroidHardwareBufferANDROID;
fn vkGetMemoryWin32HandleKHR;
fn vkGetMemoryWin32HandlePropertiesKHR;
fn vkImportSemaphoreWin32HandleKHR;
fn vkGetSemaphoreWin32HandleKHR;
fn vkImportFenceWin32HandleKHR;
fn vkGetFenceWin32HandleKHR;
fn vkGetMemoryWin32HandleNV;
fn vkAcquireFullScreenExclusiveModeEXT;
fn vkReleaseFullScreenExclusiveModeEXT;
fn vkGetDeviceGroupSurfacePresentModes2EXT;
fn vkGetPhysicalDeviceFeatures;
fn vkGetPhysicalDeviceFormatProperties;
fn vkGetPhysicalDeviceImageFormatProperties;
fn vkGetPhysicalDeviceProperties;
fn vkGetPhysicalDeviceQueueFamilyProperties;
fn vkGetPhysicalDeviceMemoryProperties;
fn vkCreateDevice;
fn vkEnumerateDeviceExtensionProperties;
fn vkEnumerateDeviceLayerProperties;
fn vkGetPhysicalDeviceSparseImageFormatProperties;
fn vkGetPhysicalDeviceFeatures2;
fn vkGetPhysicalDeviceProperties2;
fn vkGetPhysicalDeviceFormatProperties2;
fn vkGetPhysicalDeviceImageFormatProperties2;
fn vkGetPhysicalDeviceQueueFamilyProperties2;
fn vkGetPhysicalDeviceMemoryProperties2;
fn vkGetPhysicalDeviceSparseImageFormatProperties2;
fn vkGetPhysicalDeviceExternalBufferProperties;
fn vkGetPhysicalDeviceExternalFenceProperties;
fn vkGetPhysicalDeviceExternalSemaphoreProperties;
fn vkGetPhysicalDeviceSurfaceSupportKHR;
fn vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
fn vkGetPhysicalDeviceSurfaceFormatsKHR;
fn vkGetPhysicalDeviceSurfacePresentModesKHR;
fn vkGetPhysicalDevicePresentRectanglesKHR;
fn vkGetPhysicalDeviceDisplayPropertiesKHR;
fn vkGetPhysicalDeviceDisplayPlanePropertiesKHR;
fn vkGetDisplayPlaneSupportedDisplaysKHR;
fn vkGetDisplayModePropertiesKHR;
fn vkCreateDisplayModeKHR;
fn vkGetDisplayPlaneCapabilitiesKHR;
fn vkGetPhysicalDeviceFeatures2KHR;
fn vkGetPhysicalDeviceProperties2KHR;
fn vkGetPhysicalDeviceFormatProperties2KHR;
fn vkGetPhysicalDeviceImageFormatProperties2KHR;
fn vkGetPhysicalDeviceQueueFamilyProperties2KHR;
fn vkGetPhysicalDeviceMemoryProperties2KHR;
fn vkGetPhysicalDeviceSparseImageFormatProperties2KHR;
fn vkGetPhysicalDeviceExternalBufferPropertiesKHR;
fn vkGetPhysicalDeviceExternalSemaphorePropertiesKHR;
fn vkGetPhysicalDeviceExternalFencePropertiesKHR;
fn vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR;
fn vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR;
fn vkGetPhysicalDeviceSurfaceCapabilities2KHR;
fn vkGetPhysicalDeviceSurfaceFormats2KHR;
fn vkGetPhysicalDeviceDisplayProperties2KHR;
fn vkGetPhysicalDeviceDisplayPlaneProperties2KHR;
fn vkGetDisplayModeProperties2KHR;
fn vkGetDisplayPlaneCapabilities2KHR;
fn vkGetPhysicalDeviceExternalImageFormatPropertiesNV;
fn vkReleaseDisplayEXT;
fn vkGetPhysicalDeviceSurfaceCapabilities2EXT;
fn vkGetPhysicalDeviceMultisamplePropertiesEXT;
fn vkGetPhysicalDeviceCalibrateableTimeDomainsEXT;
fn vkGetPhysicalDeviceToolPropertiesEXT;
fn vkGetPhysicalDeviceCooperativeMatrixPropertiesNV;
fn vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV;
fn vkGetPhysicalDeviceWin32PresentationSupportKHR;
fn vkGetPhysicalDeviceSurfacePresentModes2EXT;
fn vkGetPhysicalDeviceWaylandPresentationSupportKHR;
fn vkGetPhysicalDeviceXcbPresentationSupportKHR;
fn vkGetPhysicalDeviceXlibPresentationSupportKHR;
fn vkAcquireXlibDisplayEXT;
fn vkGetRandROutputDisplayEXT;
fn vkDestroyInstance;
fn vkEnumeratePhysicalDevices;
fn vkGetInstanceProcAddr;
fn vkEnumeratePhysicalDeviceGroups;
fn vkDestroySurfaceKHR;
fn vkCreateDisplayPlaneSurfaceKHR;
fn vkEnumeratePhysicalDeviceGroupsKHR;
fn vkCreateDebugReportCallbackEXT;
fn vkDestroyDebugReportCallbackEXT;
fn vkDebugReportMessageEXT;
fn vkCreateDebugUtilsMessengerEXT;
fn vkDestroyDebugUtilsMessengerEXT;
fn vkSubmitDebugUtilsMessageEXT;
fn vkCreateHeadlessSurfaceEXT;
fn vkCreateAndroidSurfaceKHR;
fn vkCreateWin32SurfaceKHR;
fn vkCreateWaylandSurfaceKHR;
fn vkCreateXcbSurfaceKHR;
fn vkCreateXlibSurfaceKHR;
fn vkCreateIOSSurfaceMVK;
fn vkCreateMacOSSurfaceMVK;
fn vkCreateMetalSurfaceEXT;

int inited = 0;
int init() {
	if(inited) return 1;
	inited = 1;
	lib = LOAD_LIBRARY;
	if(!lib) return 0;
	vkGetInstanceProcAddr = GET_PROC_ADDR(lib, "vkGetInstanceProcAddr");
	vkCreateInstance = vkGetInstanceProcAddr(0, "vkCreateInstance");
	vkEnumerateInstanceExtensionProperties = vkGetInstanceProcAddr(0, "vkEnumerateInstanceExtensionProperties");
	vkEnumerateInstanceLayerProperties = vkGetInstanceProcAddr(0, "vkEnumerateInstanceLayerProperties");
	vkEnumerateInstanceVersion = vkGetInstanceProcAddr(0, "vkEnumerateInstanceVersion");
	return 1;
}

void init_instance(void* instance) {
	vkGetDeviceProcAddr = vkGetInstanceProcAddr(instance, "vkGetDeviceProcAddr");
	vkDestroyInstance = vkGetInstanceProcAddr(instance, "vkDestroyInstance");
	vkEnumeratePhysicalDevices = vkGetInstanceProcAddr(instance, "vkEnumeratePhysicalDevices");
	vkGetInstanceProcAddr = vkGetInstanceProcAddr(instance, "vkGetInstanceProcAddr");
	vkEnumeratePhysicalDeviceGroups = vkGetInstanceProcAddr(instance, "vkEnumeratePhysicalDeviceGroups");
	vkDestroySurfaceKHR = vkGetInstanceProcAddr(instance, "vkDestroySurfaceKHR");
	vkCreateDisplayPlaneSurfaceKHR = vkGetInstanceProcAddr(instance, "vkCreateDisplayPlaneSurfaceKHR");
	vkEnumeratePhysicalDeviceGroupsKHR = vkGetInstanceProcAddr(instance, "vkEnumeratePhysicalDeviceGroupsKHR");
	vkCreateDebugReportCallbackEXT = vkGetInstanceProcAddr(instance, "vkCreateDebugReportCallbackEXT");
	vkDestroyDebugReportCallbackEXT = vkGetInstanceProcAddr(instance, "vkDestroyDebugReportCallbackEXT");
	vkDebugReportMessageEXT = vkGetInstanceProcAddr(instance, "vkDebugReportMessageEXT");
	vkCreateDebugUtilsMessengerEXT = vkGetInstanceProcAddr(instance, "vkCreateDebugUtilsMessengerEXT");
	vkDestroyDebugUtilsMessengerEXT = vkGetInstanceProcAddr(instance, "vkDestroyDebugUtilsMessengerEXT");
	vkSubmitDebugUtilsMessageEXT = vkGetInstanceProcAddr(instance, "vkSubmitDebugUtilsMessageEXT");
	vkCreateHeadlessSurfaceEXT = vkGetInstanceProcAddr(instance, "vkCreateHeadlessSurfaceEXT");
	vkCreateAndroidSurfaceKHR = vkGetInstanceProcAddr(instance, "vkCreateAndroidSurfaceKHR");
	vkCreateWin32SurfaceKHR = vkGetInstanceProcAddr(instance, "vkCreateWin32SurfaceKHR");
	vkCreateWaylandSurfaceKHR = vkGetInstanceProcAddr(instance, "vkCreateWaylandSurfaceKHR");
	vkCreateXcbSurfaceKHR = vkGetInstanceProcAddr(instance, "vkCreateXcbSurfaceKHR");
	vkCreateXlibSurfaceKHR = vkGetInstanceProcAddr(instance, "vkCreateXlibSurfaceKHR");
	vkCreateIOSSurfaceMVK = vkGetInstanceProcAddr(instance, "vkCreateIOSSurfaceMVK");
	vkCreateMacOSSurfaceMVK = vkGetInstanceProcAddr(instance, "vkCreateMacOSSurfaceMVK");
	vkCreateMetalSurfaceEXT = vkGetInstanceProcAddr(instance, "vkCreateMetalSurfaceEXT");
	vkGetPhysicalDeviceFeatures = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFeatures");
	vkGetPhysicalDeviceFormatProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFormatProperties");
	vkGetPhysicalDeviceImageFormatProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceImageFormatProperties");
	vkGetPhysicalDeviceProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties");
	vkGetPhysicalDeviceQueueFamilyProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceQueueFamilyProperties");
	vkGetPhysicalDeviceMemoryProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceMemoryProperties");
	vkCreateDevice = vkGetInstanceProcAddr(instance, "vkCreateDevice");
	vkEnumerateDeviceExtensionProperties = vkGetInstanceProcAddr(instance, "vkEnumerateDeviceExtensionProperties");
	vkEnumerateDeviceLayerProperties = vkGetInstanceProcAddr(instance, "vkEnumerateDeviceLayerProperties");
	vkGetPhysicalDeviceSparseImageFormatProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSparseImageFormatProperties");
	vkGetPhysicalDeviceFeatures2 = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFeatures2");
	vkGetPhysicalDeviceProperties2 = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties2");
	vkGetPhysicalDeviceFormatProperties2 = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFormatProperties2");
	vkGetPhysicalDeviceImageFormatProperties2 = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceImageFormatProperties2");
	vkGetPhysicalDeviceQueueFamilyProperties2 = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceQueueFamilyProperties2");
	vkGetPhysicalDeviceMemoryProperties2 = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceMemoryProperties2");
	vkGetPhysicalDeviceSparseImageFormatProperties2 = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSparseImageFormatProperties2");
	vkGetPhysicalDeviceExternalBufferProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalBufferProperties");
	vkGetPhysicalDeviceExternalFenceProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalFenceProperties");
	vkGetPhysicalDeviceExternalSemaphoreProperties = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalSemaphoreProperties");
	vkGetPhysicalDeviceSurfaceSupportKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceSupportKHR");
	vkGetPhysicalDeviceSurfaceCapabilitiesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR");
	vkGetPhysicalDeviceSurfaceFormatsKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceFormatsKHR");
	vkGetPhysicalDeviceSurfacePresentModesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfacePresentModesKHR");
	vkGetPhysicalDevicePresentRectanglesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDevicePresentRectanglesKHR");
	vkGetPhysicalDeviceDisplayPropertiesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceDisplayPropertiesKHR");
	vkGetPhysicalDeviceDisplayPlanePropertiesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceDisplayPlanePropertiesKHR");
	vkGetDisplayPlaneSupportedDisplaysKHR = vkGetInstanceProcAddr(instance, "vkGetDisplayPlaneSupportedDisplaysKHR");
	vkGetDisplayModePropertiesKHR = vkGetInstanceProcAddr(instance, "vkGetDisplayModePropertiesKHR");
	vkCreateDisplayModeKHR = vkGetInstanceProcAddr(instance, "vkCreateDisplayModeKHR");
	vkGetDisplayPlaneCapabilitiesKHR = vkGetInstanceProcAddr(instance, "vkGetDisplayPlaneCapabilitiesKHR");
	vkGetPhysicalDeviceFeatures2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFeatures2KHR");
	vkGetPhysicalDeviceProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties2KHR");
	vkGetPhysicalDeviceFormatProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFormatProperties2KHR");
	vkGetPhysicalDeviceImageFormatProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceImageFormatProperties2KHR");
	vkGetPhysicalDeviceQueueFamilyProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceQueueFamilyProperties2KHR");
	vkGetPhysicalDeviceMemoryProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceMemoryProperties2KHR");
	vkGetPhysicalDeviceSparseImageFormatProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSparseImageFormatProperties2KHR");
	vkGetPhysicalDeviceExternalBufferPropertiesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalBufferPropertiesKHR");
	vkGetPhysicalDeviceExternalSemaphorePropertiesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalSemaphorePropertiesKHR");
	vkGetPhysicalDeviceExternalFencePropertiesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalFencePropertiesKHR");
	vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR = vkGetInstanceProcAddr(instance, "vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR");
	vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR");
	vkGetPhysicalDeviceSurfaceCapabilities2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceCapabilities2KHR");
	vkGetPhysicalDeviceSurfaceFormats2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceFormats2KHR");
	vkGetPhysicalDeviceDisplayProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceDisplayProperties2KHR");
	vkGetPhysicalDeviceDisplayPlaneProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceDisplayPlaneProperties2KHR");
	vkGetDisplayModeProperties2KHR = vkGetInstanceProcAddr(instance, "vkGetDisplayModeProperties2KHR");
	vkGetDisplayPlaneCapabilities2KHR = vkGetInstanceProcAddr(instance, "vkGetDisplayPlaneCapabilities2KHR");
	vkGetPhysicalDeviceExternalImageFormatPropertiesNV = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalImageFormatPropertiesNV");
	vkReleaseDisplayEXT = vkGetInstanceProcAddr(instance, "vkReleaseDisplayEXT");
	vkGetPhysicalDeviceSurfaceCapabilities2EXT = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceCapabilities2EXT");
	vkGetPhysicalDeviceMultisamplePropertiesEXT = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceMultisamplePropertiesEXT");
	vkGetPhysicalDeviceCalibrateableTimeDomainsEXT = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceCalibrateableTimeDomainsEXT");
	vkGetPhysicalDeviceToolPropertiesEXT = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceToolPropertiesEXT");
	vkGetPhysicalDeviceCooperativeMatrixPropertiesNV = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceCooperativeMatrixPropertiesNV");
	vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV");
	vkGetPhysicalDeviceWin32PresentationSupportKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceWin32PresentationSupportKHR");
	vkGetPhysicalDeviceSurfacePresentModes2EXT = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfacePresentModes2EXT");
	vkGetPhysicalDeviceWaylandPresentationSupportKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceWaylandPresentationSupportKHR");
	vkGetPhysicalDeviceXcbPresentationSupportKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceXcbPresentationSupportKHR");
	vkGetPhysicalDeviceXlibPresentationSupportKHR = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceXlibPresentationSupportKHR");
	vkAcquireXlibDisplayEXT = vkGetInstanceProcAddr(instance, "vkAcquireXlibDisplayEXT");
	vkGetRandROutputDisplayEXT = vkGetInstanceProcAddr(instance, "vkGetRandROutputDisplayEXT");
}

void init_device(void*  device) {
	vkQueueSubmit = vkGetDeviceProcAddr(device, "vkQueueSubmit");
	vkQueueWaitIdle = vkGetDeviceProcAddr(device, "vkQueueWaitIdle");
	vkQueueBindSparse = vkGetDeviceProcAddr(device, "vkQueueBindSparse");
	vkQueuePresentKHR = vkGetDeviceProcAddr(device, "vkQueuePresentKHR");
	vkQueueBeginDebugUtilsLabelEXT = vkGetDeviceProcAddr(device, "vkQueueBeginDebugUtilsLabelEXT");
	vkQueueEndDebugUtilsLabelEXT = vkGetDeviceProcAddr(device, "vkQueueEndDebugUtilsLabelEXT");
	vkQueueInsertDebugUtilsLabelEXT = vkGetDeviceProcAddr(device, "vkQueueInsertDebugUtilsLabelEXT");
	vkGetQueueCheckpointDataNV = vkGetDeviceProcAddr(device, "vkGetQueueCheckpointDataNV");
	vkQueueSetPerformanceConfigurationINTEL = vkGetDeviceProcAddr(device, "vkQueueSetPerformanceConfigurationINTEL");
	vkDestroyDevice = vkGetDeviceProcAddr(device, "vkDestroyDevice");
	vkGetDeviceQueue = vkGetDeviceProcAddr(device, "vkGetDeviceQueue");
	vkDeviceWaitIdle = vkGetDeviceProcAddr(device, "vkDeviceWaitIdle");
	vkAllocateMemory = vkGetDeviceProcAddr(device, "vkAllocateMemory");
	vkFreeMemory = vkGetDeviceProcAddr(device, "vkFreeMemory");
	vkMapMemory = vkGetDeviceProcAddr(device, "vkMapMemory");
	vkUnmapMemory = vkGetDeviceProcAddr(device, "vkUnmapMemory");
	vkFlushMappedMemoryRanges = vkGetDeviceProcAddr(device, "vkFlushMappedMemoryRanges");
	vkInvalidateMappedMemoryRanges = vkGetDeviceProcAddr(device, "vkInvalidateMappedMemoryRanges");
	vkGetDeviceMemoryCommitment = vkGetDeviceProcAddr(device, "vkGetDeviceMemoryCommitment");
	vkBindBufferMemory = vkGetDeviceProcAddr(device, "vkBindBufferMemory");
	vkBindImageMemory = vkGetDeviceProcAddr(device, "vkBindImageMemory");
	vkGetBufferMemoryRequirements = vkGetDeviceProcAddr(device, "vkGetBufferMemoryRequirements");
	vkGetImageMemoryRequirements = vkGetDeviceProcAddr(device, "vkGetImageMemoryRequirements");
	vkGetImageSparseMemoryRequirements = vkGetDeviceProcAddr(device, "vkGetImageSparseMemoryRequirements");
	vkCreateFence = vkGetDeviceProcAddr(device, "vkCreateFence");
	vkDestroyFence = vkGetDeviceProcAddr(device, "vkDestroyFence");
	vkResetFences = vkGetDeviceProcAddr(device, "vkResetFences");
	vkGetFenceStatus = vkGetDeviceProcAddr(device, "vkGetFenceStatus");
	vkWaitForFences = vkGetDeviceProcAddr(device, "vkWaitForFences");
	vkCreateSemaphore = vkGetDeviceProcAddr(device, "vkCreateSemaphore");
	vkDestroySemaphore = vkGetDeviceProcAddr(device, "vkDestroySemaphore");
	vkCreateEvent = vkGetDeviceProcAddr(device, "vkCreateEvent");
	vkDestroyEvent = vkGetDeviceProcAddr(device, "vkDestroyEvent");
	vkGetEventStatus = vkGetDeviceProcAddr(device, "vkGetEventStatus");
	vkSetEvent = vkGetDeviceProcAddr(device, "vkSetEvent");
	vkResetEvent = vkGetDeviceProcAddr(device, "vkResetEvent");
	vkCreateQueryPool = vkGetDeviceProcAddr(device, "vkCreateQueryPool");
	vkDestroyQueryPool = vkGetDeviceProcAddr(device, "vkDestroyQueryPool");
	vkGetQueryPoolResults = vkGetDeviceProcAddr(device, "vkGetQueryPoolResults");
	vkCreateBuffer = vkGetDeviceProcAddr(device, "vkCreateBuffer");
	vkDestroyBuffer = vkGetDeviceProcAddr(device, "vkDestroyBuffer");
	vkCreateBufferView = vkGetDeviceProcAddr(device, "vkCreateBufferView");
	vkDestroyBufferView = vkGetDeviceProcAddr(device, "vkDestroyBufferView");
	vkCreateImage = vkGetDeviceProcAddr(device, "vkCreateImage");
	vkDestroyImage = vkGetDeviceProcAddr(device, "vkDestroyImage");
	vkGetImageSubresourceLayout = vkGetDeviceProcAddr(device, "vkGetImageSubresourceLayout");
	vkCreateImageView = vkGetDeviceProcAddr(device, "vkCreateImageView");
	vkDestroyImageView = vkGetDeviceProcAddr(device, "vkDestroyImageView");
	vkCreateShaderModule = vkGetDeviceProcAddr(device, "vkCreateShaderModule");
	vkDestroyShaderModule = vkGetDeviceProcAddr(device, "vkDestroyShaderModule");
	vkCreatePipelineCache = vkGetDeviceProcAddr(device, "vkCreatePipelineCache");
	vkDestroyPipelineCache = vkGetDeviceProcAddr(device, "vkDestroyPipelineCache");
	vkGetPipelineCacheData = vkGetDeviceProcAddr(device, "vkGetPipelineCacheData");
	vkMergePipelineCaches = vkGetDeviceProcAddr(device, "vkMergePipelineCaches");
	vkCreateGraphicsPipelines = vkGetDeviceProcAddr(device, "vkCreateGraphicsPipelines");
	vkCreateComputePipelines = vkGetDeviceProcAddr(device, "vkCreateComputePipelines");
	vkDestroyPipeline = vkGetDeviceProcAddr(device, "vkDestroyPipeline");
	vkCreatePipelineLayout = vkGetDeviceProcAddr(device, "vkCreatePipelineLayout");
	vkDestroyPipelineLayout = vkGetDeviceProcAddr(device, "vkDestroyPipelineLayout");
	vkCreateSampler = vkGetDeviceProcAddr(device, "vkCreateSampler");
	vkDestroySampler = vkGetDeviceProcAddr(device, "vkDestroySampler");
	vkCreateDescriptorSetLayout = vkGetDeviceProcAddr(device, "vkCreateDescriptorSetLayout");
	vkDestroyDescriptorSetLayout = vkGetDeviceProcAddr(device, "vkDestroyDescriptorSetLayout");
	vkCreateDescriptorPool = vkGetDeviceProcAddr(device, "vkCreateDescriptorPool");
	vkDestroyDescriptorPool = vkGetDeviceProcAddr(device, "vkDestroyDescriptorPool");
	vkResetDescriptorPool = vkGetDeviceProcAddr(device, "vkResetDescriptorPool");
	vkAllocateDescriptorSets = vkGetDeviceProcAddr(device, "vkAllocateDescriptorSets");
	vkFreeDescriptorSets = vkGetDeviceProcAddr(device, "vkFreeDescriptorSets");
	vkUpdateDescriptorSets = vkGetDeviceProcAddr(device, "vkUpdateDescriptorSets");
	vkCreateFramebuffer = vkGetDeviceProcAddr(device, "vkCreateFramebuffer");
	vkDestroyFramebuffer = vkGetDeviceProcAddr(device, "vkDestroyFramebuffer");
	vkCreateRenderPass = vkGetDeviceProcAddr(device, "vkCreateRenderPass");
	vkDestroyRenderPass = vkGetDeviceProcAddr(device, "vkDestroyRenderPass");
	vkGetRenderAreaGranularity = vkGetDeviceProcAddr(device, "vkGetRenderAreaGranularity");
	vkCreateCommandPool = vkGetDeviceProcAddr(device, "vkCreateCommandPool");
	vkDestroyCommandPool = vkGetDeviceProcAddr(device, "vkDestroyCommandPool");
	vkResetCommandPool = vkGetDeviceProcAddr(device, "vkResetCommandPool");
	vkAllocateCommandBuffers = vkGetDeviceProcAddr(device, "vkAllocateCommandBuffers");
	vkFreeCommandBuffers = vkGetDeviceProcAddr(device, "vkFreeCommandBuffers");
	vkBindBufferMemory2 = vkGetDeviceProcAddr(device, "vkBindBufferMemory2");
	vkBindImageMemory2 = vkGetDeviceProcAddr(device, "vkBindImageMemory2");
	vkGetDeviceGroupPeerMemoryFeatures = vkGetDeviceProcAddr(device, "vkGetDeviceGroupPeerMemoryFeatures");
	vkGetImageMemoryRequirements2 = vkGetDeviceProcAddr(device, "vkGetImageMemoryRequirements2");
	vkGetBufferMemoryRequirements2 = vkGetDeviceProcAddr(device, "vkGetBufferMemoryRequirements2");
	vkGetImageSparseMemoryRequirements2 = vkGetDeviceProcAddr(device, "vkGetImageSparseMemoryRequirements2");
	vkTrimCommandPool = vkGetDeviceProcAddr(device, "vkTrimCommandPool");
	vkGetDeviceQueue2 = vkGetDeviceProcAddr(device, "vkGetDeviceQueue2");
	vkCreateSamplerYcbcrConversion = vkGetDeviceProcAddr(device, "vkCreateSamplerYcbcrConversion");
	vkDestroySamplerYcbcrConversion = vkGetDeviceProcAddr(device, "vkDestroySamplerYcbcrConversion");
	vkCreateDescriptorUpdateTemplate = vkGetDeviceProcAddr(device, "vkCreateDescriptorUpdateTemplate");
	vkDestroyDescriptorUpdateTemplate = vkGetDeviceProcAddr(device, "vkDestroyDescriptorUpdateTemplate");
	vkUpdateDescriptorSetWithTemplate = vkGetDeviceProcAddr(device, "vkUpdateDescriptorSetWithTemplate");
	vkGetDescriptorSetLayoutSupport = vkGetDeviceProcAddr(device, "vkGetDescriptorSetLayoutSupport");
	vkCreateRenderPass2 = vkGetDeviceProcAddr(device, "vkCreateRenderPass2");
	vkResetQueryPool = vkGetDeviceProcAddr(device, "vkResetQueryPool");
	vkGetSemaphoreCounterValue = vkGetDeviceProcAddr(device, "vkGetSemaphoreCounterValue");
	vkWaitSemaphores = vkGetDeviceProcAddr(device, "vkWaitSemaphores");
	vkSignalSemaphore = vkGetDeviceProcAddr(device, "vkSignalSemaphore");
	vkGetBufferDeviceAddress = vkGetDeviceProcAddr(device, "vkGetBufferDeviceAddress");
	vkGetBufferOpaqueCaptureAddress = vkGetDeviceProcAddr(device, "vkGetBufferOpaqueCaptureAddress");
	vkGetDeviceMemoryOpaqueCaptureAddress = vkGetDeviceProcAddr(device, "vkGetDeviceMemoryOpaqueCaptureAddress");
	vkCreateSwapchainKHR = vkGetDeviceProcAddr(device, "vkCreateSwapchainKHR");
	vkDestroySwapchainKHR = vkGetDeviceProcAddr(device, "vkDestroySwapchainKHR");
	vkGetSwapchainImagesKHR = vkGetDeviceProcAddr(device, "vkGetSwapchainImagesKHR");
	vkAcquireNextImageKHR = vkGetDeviceProcAddr(device, "vkAcquireNextImageKHR");
	vkGetDeviceGroupPresentCapabilitiesKHR = vkGetDeviceProcAddr(device, "vkGetDeviceGroupPresentCapabilitiesKHR");
	vkGetDeviceGroupSurfacePresentModesKHR = vkGetDeviceProcAddr(device, "vkGetDeviceGroupSurfacePresentModesKHR");
	vkAcquireNextImage2KHR = vkGetDeviceProcAddr(device, "vkAcquireNextImage2KHR");
	vkCreateSharedSwapchainsKHR = vkGetDeviceProcAddr(device, "vkCreateSharedSwapchainsKHR");
	vkGetDeviceGroupPeerMemoryFeaturesKHR = vkGetDeviceProcAddr(device, "vkGetDeviceGroupPeerMemoryFeaturesKHR");
	vkTrimCommandPoolKHR = vkGetDeviceProcAddr(device, "vkTrimCommandPoolKHR");
	vkGetMemoryFdKHR = vkGetDeviceProcAddr(device, "vkGetMemoryFdKHR");
	vkGetMemoryFdPropertiesKHR = vkGetDeviceProcAddr(device, "vkGetMemoryFdPropertiesKHR");
	vkImportSemaphoreFdKHR = vkGetDeviceProcAddr(device, "vkImportSemaphoreFdKHR");
	vkGetSemaphoreFdKHR = vkGetDeviceProcAddr(device, "vkGetSemaphoreFdKHR");
	vkCreateDescriptorUpdateTemplateKHR = vkGetDeviceProcAddr(device, "vkCreateDescriptorUpdateTemplateKHR");
	vkDestroyDescriptorUpdateTemplateKHR = vkGetDeviceProcAddr(device, "vkDestroyDescriptorUpdateTemplateKHR");
	vkUpdateDescriptorSetWithTemplateKHR = vkGetDeviceProcAddr(device, "vkUpdateDescriptorSetWithTemplateKHR");
	vkCreateRenderPass2KHR = vkGetDeviceProcAddr(device, "vkCreateRenderPass2KHR");
	vkGetSwapchainStatusKHR = vkGetDeviceProcAddr(device, "vkGetSwapchainStatusKHR");
	vkImportFenceFdKHR = vkGetDeviceProcAddr(device, "vkImportFenceFdKHR");
	vkGetFenceFdKHR = vkGetDeviceProcAddr(device, "vkGetFenceFdKHR");
	vkAcquireProfilingLockKHR = vkGetDeviceProcAddr(device, "vkAcquireProfilingLockKHR");
	vkReleaseProfilingLockKHR = vkGetDeviceProcAddr(device, "vkReleaseProfilingLockKHR");
	vkGetImageMemoryRequirements2KHR = vkGetDeviceProcAddr(device, "vkGetImageMemoryRequirements2KHR");
	vkGetBufferMemoryRequirements2KHR = vkGetDeviceProcAddr(device, "vkGetBufferMemoryRequirements2KHR");
	vkGetImageSparseMemoryRequirements2KHR = vkGetDeviceProcAddr(device, "vkGetImageSparseMemoryRequirements2KHR");
	vkCreateSamplerYcbcrConversionKHR = vkGetDeviceProcAddr(device, "vkCreateSamplerYcbcrConversionKHR");
	vkDestroySamplerYcbcrConversionKHR = vkGetDeviceProcAddr(device, "vkDestroySamplerYcbcrConversionKHR");
	vkBindBufferMemory2KHR = vkGetDeviceProcAddr(device, "vkBindBufferMemory2KHR");
	vkBindImageMemory2KHR = vkGetDeviceProcAddr(device, "vkBindImageMemory2KHR");
	vkGetDescriptorSetLayoutSupportKHR = vkGetDeviceProcAddr(device, "vkGetDescriptorSetLayoutSupportKHR");
	vkGetSemaphoreCounterValueKHR = vkGetDeviceProcAddr(device, "vkGetSemaphoreCounterValueKHR");
	vkWaitSemaphoresKHR = vkGetDeviceProcAddr(device, "vkWaitSemaphoresKHR");
	vkSignalSemaphoreKHR = vkGetDeviceProcAddr(device, "vkSignalSemaphoreKHR");
	vkGetBufferDeviceAddressKHR = vkGetDeviceProcAddr(device, "vkGetBufferDeviceAddressKHR");
	vkGetBufferOpaqueCaptureAddressKHR = vkGetDeviceProcAddr(device, "vkGetBufferOpaqueCaptureAddressKHR");
	vkGetDeviceMemoryOpaqueCaptureAddressKHR = vkGetDeviceProcAddr(device, "vkGetDeviceMemoryOpaqueCaptureAddressKHR");
	vkGetPipelineExecutablePropertiesKHR = vkGetDeviceProcAddr(device, "vkGetPipelineExecutablePropertiesKHR");
	vkGetPipelineExecutableStatisticsKHR = vkGetDeviceProcAddr(device, "vkGetPipelineExecutableStatisticsKHR");
	vkGetPipelineExecutableInternalRepresentationsKHR = vkGetDeviceProcAddr(device, "vkGetPipelineExecutableInternalRepresentationsKHR");
	vkDebugMarkerSetObjectTagEXT = vkGetDeviceProcAddr(device, "vkDebugMarkerSetObjectTagEXT");
	vkDebugMarkerSetObjectNameEXT = vkGetDeviceProcAddr(device, "vkDebugMarkerSetObjectNameEXT");
	vkGetImageViewHandleNVX = vkGetDeviceProcAddr(device, "vkGetImageViewHandleNVX");
	vkGetImageViewAddressNVX = vkGetDeviceProcAddr(device, "vkGetImageViewAddressNVX");
	vkGetShaderInfoAMD = vkGetDeviceProcAddr(device, "vkGetShaderInfoAMD");
	vkDisplayPowerControlEXT = vkGetDeviceProcAddr(device, "vkDisplayPowerControlEXT");
	vkRegisterDeviceEventEXT = vkGetDeviceProcAddr(device, "vkRegisterDeviceEventEXT");
	vkRegisterDisplayEventEXT = vkGetDeviceProcAddr(device, "vkRegisterDisplayEventEXT");
	vkGetSwapchainCounterEXT = vkGetDeviceProcAddr(device, "vkGetSwapchainCounterEXT");
	vkGetRefreshCycleDurationGOOGLE = vkGetDeviceProcAddr(device, "vkGetRefreshCycleDurationGOOGLE");
	vkGetPastPresentationTimingGOOGLE = vkGetDeviceProcAddr(device, "vkGetPastPresentationTimingGOOGLE");
	vkSetHdrMetadataEXT = vkGetDeviceProcAddr(device, "vkSetHdrMetadataEXT");
	vkSetDebugUtilsObjectNameEXT = vkGetDeviceProcAddr(device, "vkSetDebugUtilsObjectNameEXT");
	vkSetDebugUtilsObjectTagEXT = vkGetDeviceProcAddr(device, "vkSetDebugUtilsObjectTagEXT");
	vkGetImageDrmFormatModifierPropertiesEXT = vkGetDeviceProcAddr(device, "vkGetImageDrmFormatModifierPropertiesEXT");
	vkCreateValidationCacheEXT = vkGetDeviceProcAddr(device, "vkCreateValidationCacheEXT");
	vkDestroyValidationCacheEXT = vkGetDeviceProcAddr(device, "vkDestroyValidationCacheEXT");
	vkMergeValidationCachesEXT = vkGetDeviceProcAddr(device, "vkMergeValidationCachesEXT");
	vkGetValidationCacheDataEXT = vkGetDeviceProcAddr(device, "vkGetValidationCacheDataEXT");
	vkCreateAccelerationStructureNV = vkGetDeviceProcAddr(device, "vkCreateAccelerationStructureNV");
	vkDestroyAccelerationStructureKHR = vkGetDeviceProcAddr(device, "vkDestroyAccelerationStructureKHR");
	vkDestroyAccelerationStructureNV = vkGetDeviceProcAddr(device, "vkDestroyAccelerationStructureNV");
	vkGetAccelerationStructureMemoryRequirementsNV = vkGetDeviceProcAddr(device, "vkGetAccelerationStructureMemoryRequirementsNV");
	vkBindAccelerationStructureMemoryKHR = vkGetDeviceProcAddr(device, "vkBindAccelerationStructureMemoryKHR");
	vkBindAccelerationStructureMemoryNV = vkGetDeviceProcAddr(device, "vkBindAccelerationStructureMemoryNV");
	vkCreateRayTracingPipelinesNV = vkGetDeviceProcAddr(device, "vkCreateRayTracingPipelinesNV");
	vkGetRayTracingShaderGroupHandlesKHR = vkGetDeviceProcAddr(device, "vkGetRayTracingShaderGroupHandlesKHR");
	vkGetRayTracingShaderGroupHandlesNV = vkGetDeviceProcAddr(device, "vkGetRayTracingShaderGroupHandlesNV");
	vkGetAccelerationStructureHandleNV = vkGetDeviceProcAddr(device, "vkGetAccelerationStructureHandleNV");
	vkCompileDeferredNV = vkGetDeviceProcAddr(device, "vkCompileDeferredNV");
	vkGetMemoryHostPointerPropertiesEXT = vkGetDeviceProcAddr(device, "vkGetMemoryHostPointerPropertiesEXT");
	vkGetCalibratedTimestampsEXT = vkGetDeviceProcAddr(device, "vkGetCalibratedTimestampsEXT");
	vkInitializePerformanceApiINTEL = vkGetDeviceProcAddr(device, "vkInitializePerformanceApiINTEL");
	vkUninitializePerformanceApiINTEL = vkGetDeviceProcAddr(device, "vkUninitializePerformanceApiINTEL");
	vkAcquirePerformanceConfigurationINTEL = vkGetDeviceProcAddr(device, "vkAcquirePerformanceConfigurationINTEL");
	vkReleasePerformanceConfigurationINTEL = vkGetDeviceProcAddr(device, "vkReleasePerformanceConfigurationINTEL");
	vkGetPerformanceParameterINTEL = vkGetDeviceProcAddr(device, "vkGetPerformanceParameterINTEL");
	vkSetLocalDimmingAMD = vkGetDeviceProcAddr(device, "vkSetLocalDimmingAMD");
	vkGetBufferDeviceAddressEXT = vkGetDeviceProcAddr(device, "vkGetBufferDeviceAddressEXT");
	vkResetQueryPoolEXT = vkGetDeviceProcAddr(device, "vkResetQueryPoolEXT");
	vkGetGeneratedCommandsMemoryRequirementsNV = vkGetDeviceProcAddr(device, "vkGetGeneratedCommandsMemoryRequirementsNV");
	vkCreateIndirectCommandsLayoutNV = vkGetDeviceProcAddr(device, "vkCreateIndirectCommandsLayoutNV");
	vkDestroyIndirectCommandsLayoutNV = vkGetDeviceProcAddr(device, "vkDestroyIndirectCommandsLayoutNV");
	vkCreatePrivateDataSlotEXT = vkGetDeviceProcAddr(device, "vkCreatePrivateDataSlotEXT");
	vkDestroyPrivateDataSlotEXT = vkGetDeviceProcAddr(device, "vkDestroyPrivateDataSlotEXT");
	vkSetPrivateDataEXT = vkGetDeviceProcAddr(device, "vkSetPrivateDataEXT");
	vkGetPrivateDataEXT = vkGetDeviceProcAddr(device, "vkGetPrivateDataEXT");
	vkGetAndroidHardwareBufferPropertiesANDROID = vkGetDeviceProcAddr(device, "vkGetAndroidHardwareBufferPropertiesANDROID");
	vkGetMemoryAndroidHardwareBufferANDROID = vkGetDeviceProcAddr(device, "vkGetMemoryAndroidHardwareBufferANDROID");
	vkGetMemoryWin32HandleKHR = vkGetDeviceProcAddr(device, "vkGetMemoryWin32HandleKHR");
	vkGetMemoryWin32HandlePropertiesKHR = vkGetDeviceProcAddr(device, "vkGetMemoryWin32HandlePropertiesKHR");
	vkImportSemaphoreWin32HandleKHR = vkGetDeviceProcAddr(device, "vkImportSemaphoreWin32HandleKHR");
	vkGetSemaphoreWin32HandleKHR = vkGetDeviceProcAddr(device, "vkGetSemaphoreWin32HandleKHR");
	vkImportFenceWin32HandleKHR = vkGetDeviceProcAddr(device, "vkImportFenceWin32HandleKHR");
	vkGetFenceWin32HandleKHR = vkGetDeviceProcAddr(device, "vkGetFenceWin32HandleKHR");
	vkGetMemoryWin32HandleNV = vkGetDeviceProcAddr(device, "vkGetMemoryWin32HandleNV");
	vkAcquireFullScreenExclusiveModeEXT = vkGetDeviceProcAddr(device, "vkAcquireFullScreenExclusiveModeEXT");
	vkReleaseFullScreenExclusiveModeEXT = vkGetDeviceProcAddr(device, "vkReleaseFullScreenExclusiveModeEXT");
	vkGetDeviceGroupSurfacePresentModes2EXT = vkGetDeviceProcAddr(device, "vkGetDeviceGroupSurfacePresentModes2EXT");
	vkBeginCommandBuffer = vkGetDeviceProcAddr(device, "vkBeginCommandBuffer");
	vkEndCommandBuffer = vkGetDeviceProcAddr(device, "vkEndCommandBuffer");
	vkResetCommandBuffer = vkGetDeviceProcAddr(device, "vkResetCommandBuffer");
	vkCmdBindPipeline = vkGetDeviceProcAddr(device, "vkCmdBindPipeline");
	vkCmdSetViewport = vkGetDeviceProcAddr(device, "vkCmdSetViewport");
	vkCmdSetScissor = vkGetDeviceProcAddr(device, "vkCmdSetScissor");
	vkCmdSetLineWidth = vkGetDeviceProcAddr(device, "vkCmdSetLineWidth");
	vkCmdSetDepthBias = vkGetDeviceProcAddr(device, "vkCmdSetDepthBias");
	vkCmdSetBlendConstants = vkGetDeviceProcAddr(device, "vkCmdSetBlendConstants");
	vkCmdSetDepthBounds = vkGetDeviceProcAddr(device, "vkCmdSetDepthBounds");
	vkCmdSetStencilCompareMask = vkGetDeviceProcAddr(device, "vkCmdSetStencilCompareMask");
	vkCmdSetStencilWriteMask = vkGetDeviceProcAddr(device, "vkCmdSetStencilWriteMask");
	vkCmdSetStencilReference = vkGetDeviceProcAddr(device, "vkCmdSetStencilReference");
	vkCmdBindDescriptorSets = vkGetDeviceProcAddr(device, "vkCmdBindDescriptorSets");
	vkCmdBindIndexBuffer = vkGetDeviceProcAddr(device, "vkCmdBindIndexBuffer");
	vkCmdBindVertexBuffers = vkGetDeviceProcAddr(device, "vkCmdBindVertexBuffers");
	vkCmdDraw = vkGetDeviceProcAddr(device, "vkCmdDraw");
	vkCmdDrawIndexed = vkGetDeviceProcAddr(device, "vkCmdDrawIndexed");
	vkCmdDrawIndirect = vkGetDeviceProcAddr(device, "vkCmdDrawIndirect");
	vkCmdDrawIndexedIndirect = vkGetDeviceProcAddr(device, "vkCmdDrawIndexedIndirect");
	vkCmdDispatch = vkGetDeviceProcAddr(device, "vkCmdDispatch");
	vkCmdDispatchIndirect = vkGetDeviceProcAddr(device, "vkCmdDispatchIndirect");
	vkCmdCopyBuffer = vkGetDeviceProcAddr(device, "vkCmdCopyBuffer");
	vkCmdCopyImage = vkGetDeviceProcAddr(device, "vkCmdCopyImage");
	vkCmdBlitImage = vkGetDeviceProcAddr(device, "vkCmdBlitImage");
	vkCmdCopyBufferToImage = vkGetDeviceProcAddr(device, "vkCmdCopyBufferToImage");
	vkCmdCopyImageToBuffer = vkGetDeviceProcAddr(device, "vkCmdCopyImageToBuffer");
	vkCmdUpdateBuffer = vkGetDeviceProcAddr(device, "vkCmdUpdateBuffer");
	vkCmdFillBuffer = vkGetDeviceProcAddr(device, "vkCmdFillBuffer");
	vkCmdClearColorImage = vkGetDeviceProcAddr(device, "vkCmdClearColorImage");
	vkCmdClearDepthStencilImage = vkGetDeviceProcAddr(device, "vkCmdClearDepthStencilImage");
	vkCmdClearAttachments = vkGetDeviceProcAddr(device, "vkCmdClearAttachments");
	vkCmdResolveImage = vkGetDeviceProcAddr(device, "vkCmdResolveImage");
	vkCmdSetEvent = vkGetDeviceProcAddr(device, "vkCmdSetEvent");
	vkCmdResetEvent = vkGetDeviceProcAddr(device, "vkCmdResetEvent");
	vkCmdWaitEvents = vkGetDeviceProcAddr(device, "vkCmdWaitEvents");
	vkCmdPipelineBarrier = vkGetDeviceProcAddr(device, "vkCmdPipelineBarrier");
	vkCmdBeginQuery = vkGetDeviceProcAddr(device, "vkCmdBeginQuery");
	vkCmdEndQuery = vkGetDeviceProcAddr(device, "vkCmdEndQuery");
	vkCmdResetQueryPool = vkGetDeviceProcAddr(device, "vkCmdResetQueryPool");
	vkCmdWriteTimestamp = vkGetDeviceProcAddr(device, "vkCmdWriteTimestamp");
	vkCmdCopyQueryPoolResults = vkGetDeviceProcAddr(device, "vkCmdCopyQueryPoolResults");
	vkCmdPushConstants = vkGetDeviceProcAddr(device, "vkCmdPushConstants");
	vkCmdBeginRenderPass = vkGetDeviceProcAddr(device, "vkCmdBeginRenderPass");
	vkCmdNextSubpass = vkGetDeviceProcAddr(device, "vkCmdNextSubpass");
	vkCmdEndRenderPass = vkGetDeviceProcAddr(device, "vkCmdEndRenderPass");
	vkCmdExecuteCommands = vkGetDeviceProcAddr(device, "vkCmdExecuteCommands");
	vkCmdSetDeviceMask = vkGetDeviceProcAddr(device, "vkCmdSetDeviceMask");
	vkCmdDispatchBase = vkGetDeviceProcAddr(device, "vkCmdDispatchBase");
	vkCmdDrawIndirectCount = vkGetDeviceProcAddr(device, "vkCmdDrawIndirectCount");
	vkCmdDrawIndexedIndirectCount = vkGetDeviceProcAddr(device, "vkCmdDrawIndexedIndirectCount");
	vkCmdBeginRenderPass2 = vkGetDeviceProcAddr(device, "vkCmdBeginRenderPass2");
	vkCmdNextSubpass2 = vkGetDeviceProcAddr(device, "vkCmdNextSubpass2");
	vkCmdEndRenderPass2 = vkGetDeviceProcAddr(device, "vkCmdEndRenderPass2");
	vkCmdSetDeviceMaskKHR = vkGetDeviceProcAddr(device, "vkCmdSetDeviceMaskKHR");
	vkCmdDispatchBaseKHR = vkGetDeviceProcAddr(device, "vkCmdDispatchBaseKHR");
	vkCmdPushDescriptorSetKHR = vkGetDeviceProcAddr(device, "vkCmdPushDescriptorSetKHR");
	vkCmdPushDescriptorSetWithTemplateKHR = vkGetDeviceProcAddr(device, "vkCmdPushDescriptorSetWithTemplateKHR");
	vkCmdBeginRenderPass2KHR = vkGetDeviceProcAddr(device, "vkCmdBeginRenderPass2KHR");
	vkCmdNextSubpass2KHR = vkGetDeviceProcAddr(device, "vkCmdNextSubpass2KHR");
	vkCmdEndRenderPass2KHR = vkGetDeviceProcAddr(device, "vkCmdEndRenderPass2KHR");
	vkCmdDrawIndirectCountKHR = vkGetDeviceProcAddr(device, "vkCmdDrawIndirectCountKHR");
	vkCmdDrawIndexedIndirectCountKHR = vkGetDeviceProcAddr(device, "vkCmdDrawIndexedIndirectCountKHR");
	vkCmdDebugMarkerBeginEXT = vkGetDeviceProcAddr(device, "vkCmdDebugMarkerBeginEXT");
	vkCmdDebugMarkerEndEXT = vkGetDeviceProcAddr(device, "vkCmdDebugMarkerEndEXT");
	vkCmdDebugMarkerInsertEXT = vkGetDeviceProcAddr(device, "vkCmdDebugMarkerInsertEXT");
	vkCmdBindTransformFeedbackBuffersEXT = vkGetDeviceProcAddr(device, "vkCmdBindTransformFeedbackBuffersEXT");
	vkCmdBeginTransformFeedbackEXT = vkGetDeviceProcAddr(device, "vkCmdBeginTransformFeedbackEXT");
	vkCmdEndTransformFeedbackEXT = vkGetDeviceProcAddr(device, "vkCmdEndTransformFeedbackEXT");
	vkCmdBeginQueryIndexedEXT = vkGetDeviceProcAddr(device, "vkCmdBeginQueryIndexedEXT");
	vkCmdEndQueryIndexedEXT = vkGetDeviceProcAddr(device, "vkCmdEndQueryIndexedEXT");
	vkCmdDrawIndirectByteCountEXT = vkGetDeviceProcAddr(device, "vkCmdDrawIndirectByteCountEXT");
	vkCmdDrawIndirectCountAMD = vkGetDeviceProcAddr(device, "vkCmdDrawIndirectCountAMD");
	vkCmdDrawIndexedIndirectCountAMD = vkGetDeviceProcAddr(device, "vkCmdDrawIndexedIndirectCountAMD");
	vkCmdBeginConditionalRenderingEXT = vkGetDeviceProcAddr(device, "vkCmdBeginConditionalRenderingEXT");
	vkCmdEndConditionalRenderingEXT = vkGetDeviceProcAddr(device, "vkCmdEndConditionalRenderingEXT");
	vkCmdSetViewportWScalingNV = vkGetDeviceProcAddr(device, "vkCmdSetViewportWScalingNV");
	vkCmdSetDiscardRectangleEXT = vkGetDeviceProcAddr(device, "vkCmdSetDiscardRectangleEXT");
	vkCmdBeginDebugUtilsLabelEXT = vkGetDeviceProcAddr(device, "vkCmdBeginDebugUtilsLabelEXT");
	vkCmdEndDebugUtilsLabelEXT = vkGetDeviceProcAddr(device, "vkCmdEndDebugUtilsLabelEXT");
	vkCmdInsertDebugUtilsLabelEXT = vkGetDeviceProcAddr(device, "vkCmdInsertDebugUtilsLabelEXT");
	vkCmdSetSampleLocationsEXT = vkGetDeviceProcAddr(device, "vkCmdSetSampleLocationsEXT");
	vkCmdBindShadingRateImageNV = vkGetDeviceProcAddr(device, "vkCmdBindShadingRateImageNV");
	vkCmdSetViewportShadingRatePaletteNV = vkGetDeviceProcAddr(device, "vkCmdSetViewportShadingRatePaletteNV");
	vkCmdSetCoarseSampleOrderNV = vkGetDeviceProcAddr(device, "vkCmdSetCoarseSampleOrderNV");
	vkCmdBuildAccelerationStructureNV = vkGetDeviceProcAddr(device, "vkCmdBuildAccelerationStructureNV");
	vkCmdCopyAccelerationStructureNV = vkGetDeviceProcAddr(device, "vkCmdCopyAccelerationStructureNV");
	vkCmdTraceRaysNV = vkGetDeviceProcAddr(device, "vkCmdTraceRaysNV");
	vkCmdWriteAccelerationStructuresPropertiesKHR = vkGetDeviceProcAddr(device, "vkCmdWriteAccelerationStructuresPropertiesKHR");
	vkCmdWriteAccelerationStructuresPropertiesNV = vkGetDeviceProcAddr(device, "vkCmdWriteAccelerationStructuresPropertiesNV");
	vkCmdWriteBufferMarkerAMD = vkGetDeviceProcAddr(device, "vkCmdWriteBufferMarkerAMD");
	vkCmdDrawMeshTasksNV = vkGetDeviceProcAddr(device, "vkCmdDrawMeshTasksNV");
	vkCmdDrawMeshTasksIndirectNV = vkGetDeviceProcAddr(device, "vkCmdDrawMeshTasksIndirectNV");
	vkCmdDrawMeshTasksIndirectCountNV = vkGetDeviceProcAddr(device, "vkCmdDrawMeshTasksIndirectCountNV");
	vkCmdSetExclusiveScissorNV = vkGetDeviceProcAddr(device, "vkCmdSetExclusiveScissorNV");
	vkCmdSetCheckpointNV = vkGetDeviceProcAddr(device, "vkCmdSetCheckpointNV");
	vkCmdSetPerformanceMarkerINTEL = vkGetDeviceProcAddr(device, "vkCmdSetPerformanceMarkerINTEL");
	vkCmdSetPerformanceStreamMarkerINTEL = vkGetDeviceProcAddr(device, "vkCmdSetPerformanceStreamMarkerINTEL");
	vkCmdSetPerformanceOverrideINTEL = vkGetDeviceProcAddr(device, "vkCmdSetPerformanceOverrideINTEL");
	vkCmdSetLineStippleEXT = vkGetDeviceProcAddr(device, "vkCmdSetLineStippleEXT");
	vkCmdSetCullModeEXT = vkGetDeviceProcAddr(device, "vkCmdSetCullModeEXT");
	vkCmdSetFrontFaceEXT = vkGetDeviceProcAddr(device, "vkCmdSetFrontFaceEXT");
	vkCmdSetPrimitiveTopologyEXT = vkGetDeviceProcAddr(device, "vkCmdSetPrimitiveTopologyEXT");
	vkCmdSetViewportWithCountEXT = vkGetDeviceProcAddr(device, "vkCmdSetViewportWithCountEXT");
	vkCmdSetScissorWithCountEXT = vkGetDeviceProcAddr(device, "vkCmdSetScissorWithCountEXT");
	vkCmdBindVertexBuffers2EXT = vkGetDeviceProcAddr(device, "vkCmdBindVertexBuffers2EXT");
	vkCmdSetDepthTestEnableEXT = vkGetDeviceProcAddr(device, "vkCmdSetDepthTestEnableEXT");
	vkCmdSetDepthWriteEnableEXT = vkGetDeviceProcAddr(device, "vkCmdSetDepthWriteEnableEXT");
	vkCmdSetDepthCompareOpEXT = vkGetDeviceProcAddr(device, "vkCmdSetDepthCompareOpEXT");
	vkCmdSetDepthBoundsTestEnableEXT = vkGetDeviceProcAddr(device, "vkCmdSetDepthBoundsTestEnableEXT");
	vkCmdSetStencilTestEnableEXT = vkGetDeviceProcAddr(device, "vkCmdSetStencilTestEnableEXT");
	vkCmdSetStencilOpEXT = vkGetDeviceProcAddr(device, "vkCmdSetStencilOpEXT");
	vkCmdPreprocessGeneratedCommandsNV = vkGetDeviceProcAddr(device, "vkCmdPreprocessGeneratedCommandsNV");
	vkCmdExecuteGeneratedCommandsNV = vkGetDeviceProcAddr(device, "vkCmdExecuteGeneratedCommandsNV");
	vkCmdBindPipelineShaderGroupNV = vkGetDeviceProcAddr(device, "vkCmdBindPipelineShaderGroupNV");
}

